'use client';

import Giscus from '@giscus/react';
import { useTheme } from 'next-themes';
import { giscusConfig } from '@/lib/shared';

// Renders nothing until `giscusConfig.repoId`/`categoryId` (lib/shared.ts)
// are filled in — both are generated by https://giscus.app once GitHub
// Discussions and the giscus app are enabled on the `roves` repo, a
// one-time manual step only the repo owner can do.
export function GiscusComments() {
  const { resolvedTheme } = useTheme();
  if (!giscusConfig.repoId || !giscusConfig.categoryId) return null;

  return (
    <div className="mt-12 border-t border-fd-border pt-8">
      <Giscus
        repo={giscusConfig.repo}
        repoId={giscusConfig.repoId}
        category={giscusConfig.category}
        categoryId={giscusConfig.categoryId}
        mapping="pathname"
        strict="0"
        reactionsEnabled="1"
        emitMetadata="0"
        inputPosition="top"
        theme={resolvedTheme === 'dark' ? 'dark' : 'light'}
        lang="en"
        loading="lazy"
      />
    </div>
  );
}
